# Generated by Django 6.0 on 2025-12-17 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=12, verbose_name='Ідентифікатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата зміни')),
                ('full_name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('channel', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('chat', 'Чат бот'), ('telegram', 'Telegram'), ('viber', 'Viber')], max_length=20, verbose_name="Канал зв'язку")),
                ('request_type', models.CharField(choices=[('bug', 'Помилка ПЗ'), ('feature', 'Новий функціонал'), ('question', 'Консультація'), ('access', 'Надання доступу'), ('complaint', 'Скарга')], max_length=20, verbose_name='Тип звернення')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('pending', 'Очікування'), ('resolved', 'Вирішено'), ('closed', 'Зачинено')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department', verbose_name='Департамент')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
