# Generated by Django 6.0 on 2025-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_department_options_remove_department_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/', verbose_name='Файл'),
        ),
    ]
